CREATE TABLE "dbo.updatennv2" (
	"TRANSID" INTEGER NULL DEFAULT NULL,
	"PROVINCECODE" DOUBLE PRECISION NULL DEFAULT NULL,
	"DIVCODE" DOUBLE PRECISION NULL DEFAULT NULL,
	"CITYCODE" DOUBLE PRECISION NULL DEFAULT NULL
)
;
COMMENT ON COLUMN "dbo.updatennv2"."TRANSID" IS E'';
COMMENT ON COLUMN "dbo.updatennv2"."PROVINCECODE" IS E'';
COMMENT ON COLUMN "dbo.updatennv2"."DIVCODE" IS E'';
COMMENT ON COLUMN "dbo.updatennv2"."CITYCODE" IS E'';
